INSERT INTO ListItem (ParentId, Name, [Description], Value, StatusId, LastUpdateTimestamp, LastUpdateAccountId) SELECT liat.ListItemId, 'Palliative', 'Palliative', '20', lisa.ListItemId, getdate(), (SELECT TOP 1 AccountId FROM Account ORDER BY DateCreatedTimestamp) FROM ListItem lis INNER JOIN ListItem lisa ON (lis.ListItemId = lisa.ParentId AND lis.Name = 'Status' AND lisa.Name = 'Active') INNER JOIN ListItem liat ON (liat.ParentId IS NULL AND liat.Name = 'ImpairmentClass');
INSERT INTO ListItem (ParentId, Name, [Description], Value, StatusId, LastUpdateTimestamp, LastUpdateAccountId) SELECT liat.ListItemId, 'Home Based Care', 'Home Based Care', '21', lisa.ListItemId, getdate(), (SELECT TOP 1 AccountId FROM Account ORDER BY DateCreatedTimestamp) FROM ListItem lis INNER JOIN ListItem lisa ON (lis.ListItemId = lisa.ParentId AND lis.Name = 'Status' AND lisa.Name = 'Active') INNER JOIN ListItem liat ON (liat.ParentId IS NULL AND liat.Name = 'ImpairmentClass');
INSERT INTO ListItem (ParentId, Name, [Description], Value, StatusId, LastUpdateTimestamp, LastUpdateAccountId) SELECT liat.ListItemId, 'Long Term Care', 'Long Term Care', '22', lisa.ListItemId, getdate(), (SELECT TOP 1 AccountId FROM Account ORDER BY DateCreatedTimestamp) FROM ListItem lis INNER JOIN ListItem lisa ON (lis.ListItemId = lisa.ParentId AND lis.Name = 'Status' AND lisa.Name = 'Active') INNER JOIN ListItem liat ON (liat.ParentId IS NULL AND liat.Name = 'ImpairmentClass');
INSERT INTO ListItem (ParentId, Name, [Description], Value, StatusId, LastUpdateTimestamp, LastUpdateAccountId) SELECT liat.ListItemId, 'Social Functioning related Disabilities and Needs', 'Social Functioning related Disabilities and Needs', '23', lisa.ListItemId, getdate(), (SELECT TOP 1 AccountId FROM Account ORDER BY DateCreatedTimestamp) FROM ListItem lis INNER JOIN ListItem lisa ON (lis.ListItemId = lisa.ParentId AND lis.Name = 'Status' AND lisa.Name = 'Active') INNER JOIN ListItem liat ON (liat.ParentId IS NULL AND liat.Name = 'ImpairmentClass');
INSERT INTO ListItem (ParentId, Name, [Description], Value, StatusId, LastUpdateTimestamp, LastUpdateAccountId) SELECT liat.ListItemId, 'OPD Based Care', 'OPD Based Care', '24', lisa.ListItemId, getdate(), (SELECT TOP 1 AccountId FROM Account ORDER BY DateCreatedTimestamp) FROM ListItem lis INNER JOIN ListItem lisa ON (lis.ListItemId = lisa.ParentId AND lis.Name = 'Status' AND lisa.Name = 'Active') INNER JOIN ListItem liat ON (liat.ParentId IS NULL AND liat.Name = 'ImpairmentClass');

UPDATE	liic
SET		SortOrder = CONVERT(int, liic.Value)
FROM	ListItem liic
		INNER JOIN ListItem liat ON (liat.ParentId IS NULL AND liat.Name = 'ImpairmentClass' AND liic.ParentId = liat.ListItemId);