//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SADFM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.AccountsLastUpdated = new HashSet<Account>();
            this.Audits = new HashSet<Audit>();
            this.FunderAccountPermissions = new HashSet<FunderAccountPermission>();
            this.ListItems = new HashSet<ListItem>();
            this.Messages = new HashSet<Message>();
            this.MessageRecipients = new HashSet<MessageRecipient>();
            this.Providers = new HashSet<Provider>();
            this.ProviderAccountPermissions = new HashSet<ProviderAccountPermission>();
            this.Sessions = new HashSet<Session>();
            this.AccountRoles = new HashSet<AccountRole>();
            this.ScalePermissions = new HashSet<ScalePermission>();
            this.Cases = new HashSet<Case>();
            this.ProviderServiceTypes = new HashSet<ProviderServiceType>();
            this.Patients = new HashSet<Patient>();
            this.PatientSupportServices = new HashSet<PatientSupportService>();
            this.PatientScales = new HashSet<PatientScale>();
            this.PatientProviders = new HashSet<PatientProvider>();
            this.Visits = new HashSet<Visit>();
        }
    
        public System.Guid AccountId { get; set; }
        public System.Guid AccountTypeId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string EmailAddress { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> InvalidLoginAttempts { get; set; }
        public System.Guid StatusId { get; set; }
        public Nullable<System.Guid> LanguageId { get; set; }
        public bool FirstSignIn { get; set; }
        public System.DateTime DateCreatedTimestamp { get; set; }
        public System.DateTime LastUpdateTimestamp { get; set; }
        public System.Guid LastUpdateAccountId { get; set; }
        public Nullable<System.Guid> TitleId { get; set; }
        public string IDNumberType { get; set; }
        public string IDNumber { get; set; }
        public string ContactNumber { get; set; }
        public byte[] Avatar { get; set; }
        public Nullable<System.Guid> SecurityQuestionId { get; set; }
        public string SecurityQuestionAnswer { get; set; }
        public Nullable<System.DateTime> DisclaimerAgreeTimestamp { get; set; }
        public bool ResetBySuperAdmin { get; set; }
        public string HPSCANumber { get; set; }
        public string PracticeNumber { get; set; }
        public Nullable<System.Guid> ProfessionalBodyId { get; set; }
        public string RegistrationNumber { get; set; }
    
        public virtual ListItem AccountType { get; set; }
        public virtual ListItem Language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> AccountsLastUpdated { get; set; }
        public virtual Account LastUpdateAccount { get; set; }
        public virtual ListItem Status { get; set; }
        public virtual ListItem Title { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Audit> Audits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FunderAccountPermission> FunderAccountPermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListItem> ListItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageRecipient> MessageRecipients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Provider> Providers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderAccountPermission> ProviderAccountPermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Sessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountRole> AccountRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScalePermission> ScalePermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Case> Cases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderServiceType> ProviderServiceTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient> Patients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientSupportService> PatientSupportServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientScale> PatientScales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientProvider> PatientProviders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visit> Visits { get; set; }
        public virtual ListItem ListItem4 { get; set; }
    }
}
