//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SADFM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Case()
        {
            this.PatientProviders = new HashSet<PatientProvider>();
            this.Visits = new HashSet<Visit>();
        }
    
        public System.Guid CaseId { get; set; }
        public System.Guid PatientId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.Guid ICD10Id { get; set; }
        public System.DateTime DateCreatedTimestamp { get; set; }
        public System.DateTime LastUpdateTimestamp { get; set; }
        public System.Guid LastUpdateAccountId { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.Guid> ImpairmentGroupId { get; set; }
        public Nullable<System.Guid> AdmissionStatusId { get; set; }
        public Nullable<System.DateTime> LastTreatment { get; set; }
        public string LastTreatmentNote { get; set; }
        public string ReferringDoctor { get; set; }
        public string ReferringDoctorContact { get; set; }
        public string ReferringDoctorEmail { get; set; }
        public string ReferringDoctorPracticeNumber { get; set; }
        public string TreatingDoctor { get; set; }
        public string TreatingDoctorContact { get; set; }
        public string TreatingDoctorEmail { get; set; }
        public string TreatingDoctorPracticeNumber { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ListItem ICD10 { get; set; }
        public virtual ListItem ImpairmentGroup { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual ListItem AdmissionStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientProvider> PatientProviders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
