//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SADFM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListItemLabel
    {
        public System.Guid ListItemId { get; set; }
        public System.Guid LanguageId { get; set; }
        public string Label { get; set; }
    
        public virtual ListItem Language { get; set; }
        public virtual ListItem ListItem { get; set; }
    }
}
