//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SADFM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Message()
        {
            this.MessageRecipients = new HashSet<MessageRecipient>();
        }
    
        public System.Guid MessageId { get; set; }
        public System.Guid PatientId { get; set; }
        public System.Guid FromAccountId { get; set; }
        public System.DateTime SentTimestamp { get; set; }
        public string Body { get; set; }
        public bool Archived { get; set; }
    
        public virtual Account FromAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageRecipient> MessageRecipients { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
