//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SADFM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientProvider
    {
        public System.Guid PatientProviderId { get; set; }
        public System.Guid PatientId { get; set; }
        public System.Guid ProviderId { get; set; }
        public Nullable<System.Guid> CaseId { get; set; }
        public System.Guid AccountId { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime AssignedTimestamp { get; set; }
        public Nullable<System.DateTime> DischargeTimestamp { get; set; }
        public System.DateTime LastUpdateTimestamp { get; set; }
        public System.Guid LastUpdateAccountId { get; set; }
        public Nullable<System.Guid> ReasonForAdmissionId { get; set; }
        public Nullable<System.DateTime> ICD10CodeTimestamp { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Case Case { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual ListItem ListItem { get; set; }
    }
}
