//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SADFM.DatabaseMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public System.Guid AuditId { get; set; }
        public string TableName { get; set; }
        public string FieldName { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public System.Guid AccountId { get; set; }
        public System.Guid PrimaryKeyId { get; set; }
        public System.Guid ChangeTypeId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ListItem ListItem { get; set; }
    }
}
