//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SADFM.DatabaseMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Cases = new HashSet<Case>();
            this.Messages = new HashSet<Message>();
            this.PatientImpairmentGroupHistories = new HashSet<PatientImpairmentGroupHistory>();
            this.PatientProviders = new HashSet<PatientProvider>();
            this.PatientScales = new HashSet<PatientScale>();
            this.PatientSupportServices = new HashSet<PatientSupportService>();
            this.Visits = new HashSet<Visit>();
        }
    
        public System.Guid PatientId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.Guid> GenderId { get; set; }
        public Nullable<System.Guid> RaceId { get; set; }
        public string IDNumber { get; set; }
        public Nullable<System.Guid> MedicalSchemeId { get; set; }
        public Nullable<System.Guid> TitleId { get; set; }
        public string ContactNumber { get; set; }
        public string Street { get; set; }
        public string PostalCode { get; set; }
        public Nullable<System.Guid> CountryId { get; set; }
        public string NextOfKinName { get; set; }
        public string NextOfKinContact { get; set; }
        public string MedicalSchemeMembershipNumber { get; set; }
        public System.DateTime DateCreatedTimestamp { get; set; }
        public System.DateTime LastUpdateTimestamp { get; set; }
        public System.Guid LastUpdateAccountId { get; set; }
        public byte[] Avatar { get; set; }
        public Nullable<System.Guid> ProvinceId { get; set; }
        public Nullable<System.Guid> CityId { get; set; }
        public string NextOfKinEmail { get; set; }
        public string NextOfKinRelationship { get; set; }
        public Nullable<System.Guid> AdmitFromId { get; set; }
        public Nullable<System.Guid> DischargeToId { get; set; }
        public Nullable<System.Guid> ResidentialEnvironmentId { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Case> Cases { get; set; }
        public virtual ListItem City { get; set; }
        public virtual ListItem AdmitFrom { get; set; }
        public virtual ListItem Country { get; set; }
        public virtual ListItem DischargeTo { get; set; }
        public virtual ListItem Gender { get; set; }
        public virtual ListItem MedicalScheme { get; set; }
        public virtual ListItem Race { get; set; }
        public virtual ListItem ResidentialEnviromentType { get; set; }
        public virtual ListItem Title { get; set; }
        public virtual ListItem Province { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientImpairmentGroupHistory> PatientImpairmentGroupHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientProvider> PatientProviders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientScale> PatientScales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientSupportService> PatientSupportServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
