//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SADFM.DatabaseMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientScale
    {
        public System.Guid PatientScaleId { get; set; }
        public System.Guid PatientId { get; set; }
        public System.Guid ScaleId { get; set; }
        public System.Guid FrequencyId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTimestamp { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
        public Nullable<System.Guid> ProviderId { get; set; }
        public Nullable<System.Guid> StatusId { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ListItem Frequency { get; set; }
        public virtual ListItem Scale { get; set; }
        public virtual ListItem Status { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
