//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SADFM.DatabaseMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientImpairmentGroupHistory
    {
        public System.Guid PatientImpairmentGroupHistoryId { get; set; }
        public Nullable<System.Guid> ImpairmentGroupId { get; set; }
        public System.Guid PatientId { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual ListItem ListItem { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
