//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SADFM.DatabaseMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderServiceType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProviderServiceType()
        {
            this.ProviderServiceTypeScales = new HashSet<ProviderServiceTypeScale>();
        }
    
        public System.Guid ProviderServiceTypeId { get; set; }
        public System.Guid ProviderId { get; set; }
        public System.Guid ServiceTypeId { get; set; }
        public string ContactNumber { get; set; }
        public string Street { get; set; }
        public string PostalCode { get; set; }
        public Nullable<System.Guid> CountryId { get; set; }
        public System.DateTime DateCreatedTimestamp { get; set; }
        public System.DateTime LastUpdateTimestamp { get; set; }
        public System.Guid LastUpdateAccountId { get; set; }
        public Nullable<System.Guid> ProvinceId { get; set; }
        public Nullable<System.Guid> CityId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ListItem ListItem { get; set; }
        public virtual ListItem ListItem1 { get; set; }
        public virtual ListItem ListItem2 { get; set; }
        public virtual ListItem ListItem3 { get; set; }
        public virtual Provider Provider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderServiceTypeScale> ProviderServiceTypeScales { get; set; }
    }
}
