//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SADFM.DatabaseMigrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Visit()
        {
            this.VisitAttachments = new HashSet<VisitAttachment>();
            this.VisitScores = new HashSet<VisitScore>();
        }
    
        public System.Guid VisitId { get; set; }
        public System.Guid PatientId { get; set; }
        public System.DateTime VisitDate { get; set; }
        public Nullable<int> VisitDuration { get; set; }
        public string VisitNotes { get; set; }
        public Nullable<System.Guid> CaseId { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public Nullable<System.DateTime> DischargeDate { get; set; }
        public Nullable<double> Temperature { get; set; }
        public Nullable<int> HeartRate { get; set; }
        public Nullable<bool> HeartRateRegular { get; set; }
        public string HeartRateNote { get; set; }
        public Nullable<int> BloodPressureSystolic { get; set; }
        public Nullable<int> BloodPressureDiastolic { get; set; }
        public Nullable<int> RespiratoryRate { get; set; }
        public Nullable<bool> RespiratoryRateRegular { get; set; }
        public string RespiratoryRateNote { get; set; }
        public Nullable<int> PulseOximetry { get; set; }
        public Nullable<bool> SupplementaryOxygen { get; set; }
        public string SupplementaryOxygenNote { get; set; }
        public Nullable<double> Glucose { get; set; }
        public string ExtraNote { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Case Case { get; set; }
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitAttachment> VisitAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitScore> VisitScores { get; set; }
    }
}
